SELECT * FROM EMP;

-- EXAMPLE OF PROJECTION
SELECT ENAME FROM EMP;

-- EXAMPLE OF SELECTION
SELECT * FROM EMP
WHERE SAL > 4000;

-- EXAMPLE OF SELECTION AND PROJECTION
SELECT ENAME FROM EMP
WHERE SAL > 4000;

-- EXAMPLE FOR WHERE CLAUSE rownum
select ENAME, SAL FROM EMP
WHERE rownum <
order by sal DESC;

-- EXAMPLE OF DISTINCT 
SELECT DISTINCT JOB FROM EMP;

-- COMPARISON OPERATOR - BETWEEN
SELECT * FROM EMP
WHERE SAL BETWEEN 2000 and 4000;




SELECT * FROM DEPT;
SELECT DNAME from dept
WHERE DNAME LIKE 'S%';


SELECT DNAME FROM dept
WHERE LOC = 'CHICAGO';

SELECT DNAME FROM dept
WHERE DNAME NOT LIKE '%S';

Select DNAME from dept
ORDER BY DNAME DESC;

-- IN OPERATOR - BETWEEN
select * from dept where deptno IN (20,30);

-- NOT IN OPERATOR - BETWEEN
select * from dept where deptno NOT IN (20,30);

SELECT * from EMP
WHERE ENAME LIKE 'SH';

select ename, comm from EMP WHERE COMM IS NOT null;

select ename as "Employee Name" from emp;


Select * from emp order by deptno DESC, JOB ASC;

-- TO_NUMBER QUERY
SELECT ENAME, SAL FROM EMP
WHERE TO_NUMBER('1,000','9,000')< SAL;

SELECT TO_NUMBER('8,400','9,999') FROM DUAL;

-- TO_CHAR QUERY
SELECT TO_CHAR(786757670,'$99,99,99,999') FROM DUAL;

SELECT * FROM EMP
WHERE TO_CHAR(HIREDATE,'YYYY') IN (1982,1987);

Select ename, to_char(hiredate,'MONTH YYYY') AS  "Joining Month" from emp;

SELECT TO_CHAR(SYSDATE,'DDspth "DAY OF "MMspth "MONTH OF " YEAR') FROM DUAL;

SELECT * FROM EMP
WHERE TO_CHAR(HIREDATE,'YYYY')=1987;

SELECT * FROM EMP
WHERE TO_CHAR(HIREDATE,'MM')=04;

-- SINGLE ROW FUNCTION
SELECT UPPER(ENAME) FROM EMP;

-- MULTIPLE ROW FUNCTION WITH TO_CHAR FUNCTIONALITY
SELECT TO_CHAR(AVG(SAL),'$9999.00')FROM EMP;

-- pading query
SELECT ENAME, RPAD(SAL,10,'*') FROM EMP;
SELECT ENAME, LPAD(SAL,10,'*') FROM EMP;

-- InitCap query
SELECT initcap('darshan chaudhari') from dual;

-- DISPLAY HIGHEST SALARY AND LOWERST SALARY USING MIN AND MAX

SELECT MIN(SAL) FROM EMP;
SELECT MAX(SAL) FROM EMP;     

-- CONCAT QUERY
SELECT concat(ENAME, SAL)  FROM EMP;
select concat(concat(ename, ' , '),job) AS "EMPLOYEE INFORMATION" from emp;

-- round query
SELECT HIREDATE,ROUND(HIREDATE, 'MONTH') FROM EMP;

-- assignment on Add_months
SELECT HIREDATE, ADD_MONTHS(HIREDATE,'36') AS "CONTRACT COMPLETTION DATE" FROM EMP;

-- nvl FUNCTION
select ename, sal, comm, sal+NVL(comm,0) as "Net Income" from emp;

-- Rank function query - ASC
SELECT ENAME, SAL , DENSE_RANK() OVER(ORDER BY SAL ) FROM EMP;
-- Rank function query - DESC
SELECT ENAME, SAL , RANK() OVER(ORDER BY SAL DESC ) AS "ERANK" FROM EMP;

-- EQUIJOIN QUERY
SELECT ENAME, DNAME FROM EMP e JOIN DEPT d on (e.deptno= d.deptno);
--another syntax 
SELECT ENAME, DNAME FROM EMP JOIN DEPT using (deptno);


--NON EQUI JOIN
SELECT ENAME, SAL, GRADE FROM EMP e join salgrade d on (e.sal between d.losal and d.hisal);


-- INNER JOIN
SELECT ENAME, DNAME FROM EMP e JOIN DEPT d using (deptno);


-- LEFT JOIN
SELECT ENAME, DNAME FRO
M EMP e LEFT JOIN DEPT d using (deptno);

-- RIGHT JOIN
SELECT ENAME, DNAME FROM EMP e RIGHT JOIN DEPT d using (deptno);

--FULL JOIN
SELECT ENAME, DNAME FROM EMP e FULL JOIN DEPT d using (deptno);


SELECT * FROM TAB;

SELECT * FROM USER_TABLES;

SELECT * FROM USER_VIEWS;

SELECT * FROM USER_CONSTRAINTS;

SELECT * FROM USER_INDEXES;

SELECT * FROM USER_SEQUENCES;